version: '3.10.8'

services:
 web:
  build: .
  command: python /code/manage.py runserver 0.0.0.0:8000
  environment:
    - SECRET_KEY=b2s5g0hnyr)n5@y8c(oxv&o2s^jk3u1t86iz_djv&dk1m$y!nt
    - DEBUG=1
  volumes:
    - .:/code
  ports:
    - 8000:8000
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started
 redis:
  image: redis
 db:
  image: postgres:15
  volumes:
    - postgres_data:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: 'Sistemas123'
  healthcheck:
      test: "exit 0"

volumes:
  postgres_data:
