version: '3.10'

services:
 web:
  build: .
  command: python /code/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - 8000:8000
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started
 redis:
  image: redis
 db:
  image: postgres:15
  volumes:
    - postgres_data:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: 'Sistemas123'
  healthcheck:
      test: "exit 0"

volumes:
  postgres_data:
